### ISSUE TITLE
locale.getdefaultlocale is deprecated

### ISSUE THREAD

**Issue by graingert-coef** [census-instrumentation/opencensus-python#1238]
getdefaultlocale is called here:

https://github.com/census-instrumentation/opencensus-python/blob/977d93824e24b73f2cffca03301b7b83c1929fb4/contrib/opencensus-ext-azure/opencensus/ext/azure/common/utils.py#L30

and results in a deprecation warning:

```
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/config.py", line 735, in configure_handler
    klass = self.resolve(cname)
            ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/logging/config.py", line 402, in resolve
    self.importer(used)
  File "/home/vsts/work/1/s/venv/lib/python3.11/site-packages/opencensus/ext/azure/log_exporter/__init__.py", line 22, in <module>
    from opencensus.ext.azure.common import Options, utils
  File "/home/vsts/work/1/s/venv/lib/python3.11/site-packages/opencensus/ext/azure/common/utils.py", line 30, in <module>
    'ai.device.locale': locale.getdefaultlocale()[0],
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/locale.py", line 559, in getdefaultlocale
    warnings._deprecated(
  File "/opt/hostedtoolcache/Python/3.11.7/x64/lib/python3.11/warnings.py", line 514, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
```

**Comment by graingert-coef** [comment]
see also https://github.com/python/cpython/issues/90817

**Comment by lzchen** [comment]
@graingert-coef 

Do you see this warning on Python 3.9? OpenCensus only supports up to [Python 3.9](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/setup.py#L38)

**Comment by graingert-coef** [comment]
@lzchen I'm using this on Python 3.11

**Comment by IndrajeetPatil** [comment]
I am also seeing this warning with `Python 3.13`.

Seems to be coming from here?

https://github.com/census-instrumentation/opencensus-python/blob/2275bd06bd56d24e987734d82817bcfca7b5909c/contrib/opencensus-ext-azure/opencensus/ext/azure/common/utils.py#L30

Any plans to have a new release to fix this warning?
