### ISSUE TITLE
Error when using google_cloud_clientlibs: "integration 'NoopTracer' object has no attribute 'span_context'"

### ISSUE THREAD

**Issue by bshaffer** [census-instrumentation/opencensus-python#134]
With the latest release, `0.1.3`, I am getting the following exception when using the `google_cloud_clientlibs` trace integration:

```
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 701, in channel_spin
    completed_call = event.tag(event)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 174, in handle_event
    callback()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 313, in <lambda>
    self._state.callbacks.append(lambda: fn(self))
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/ext/grpc/client_interceptor.py", line 122, in callback
    self._tracer.end_span()
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/tracer.py", line 116, in end_span
    self.tracer.end_span()
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/tracers/context_tracer.py", line 112, in end_span
    self.exporter.export(span_json)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 145, in export
    self.transport.export(trace)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/exporters/transports/sync.py", line 23, in export
    self.exporter.emit(trace)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 142, in emit
    self.client.batch_write_spans(name, stackdriver_spans)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/trace/client.py", line 104, in batch_write_spans
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/trace/_gax.py", line 91, in batch_write_spans
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/trace_v2/gapic/trace_service_client.py", line 187, in batch_write_spans
    self._batch_write_spans(request, retry=retry, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/grpc_helpers.py", line 54, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 141, in __call__
    return call_future.result()
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 110, in result
    raise self._exception
AttributeError: 'NoopTracer' object has no attribute 'span_context'
```

Here is my code:

```py
    exporter = stackdriver_exporter.StackdriverExporter(
        project_id=project)
    # exporter = print_exporter.PrintExporter()
    spanCtx = tracer_module.SpanContext(trace_id=str(traceId))
    tracer = tracer_module.Tracer(exporter=exporter, span_context=spanCtx)
    config_integration.trace_integrations(['google_cloud_clientlibs'])
```

**Comment by liyanhui1228** [comment]
Hi @bshaffer, thanks for reporting! PR #133 is fixing this problem. This is because the tracer is stored in thread_local and not shared between threads, so in the threads that cannot get a real tracer from the context, it just uses a NoopTracer. Please use the code in the latest PR for a quick fix.
