### ISSUE TITLE
TypeError exception with gRPC

### ISSUE THREAD

**Issue by ocervell** [census-instrumentation/opencensus-python#263]
I'm getting the following exception while trying to set up gRPC tracing for Forseti:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/services/inventory/inventory.py", line 255, in do_inventory
    background)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/services/inventory/inventory.py", line 202, in run_import
    background)
  File "/usr/local/lib/python2.7/dist-packages/forseti_security-2.1.0-py2.7.egg/google/cloud/forseti/services/client.py", line 295, in new_model
    background=background))
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 201, in __call__
    credentials=credentials)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 225, in _with_call
    continuation, client_call_details, request)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/ext/grpc/client_interceptor.py", line 174, in intercept_unary_unary
    response.add_done_callback(self._callback(current_span))
  File "/usr/local/lib/python2.7/dist-packages/grpc/_interceptor.py", line 186, in add_done_callback
    fn(self)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/ext/grpc/client_interceptor.py", line 141, in callback
    self._trace_future_exception(future_response)
  File "/usr/local/lib/python2.7/dist-packages/opencensus/trace/ext/grpc/client_interceptor.py", line 148, in _trace_future_exception
    exception = response.exception(timeout=TIMEOUT)
TypeError: exception() got an unexpected keyword argument 'timeout'
```

After manually removing the 'timeout=TIMEOUT' it works without errors, but `timeout` seems to be important here.

Do we know what's the object class for `exception()` here so that I can send out a patch on that class ?

This is currently a breaking bug for gRPC client integration in Python.

**Comment by ocervell** [comment]
Moving to
