### ISSUE TITLE
stats/exporters: StackDriver exporter fails with "One or more Timeseries could not be written"

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-python#350]
Am using OpenCensus-Python 0.1.8

and on trying out the example at https://opencensus.io/guides/integrations/memcached/python/#end-to-end-example

I get this printed to my console, exceptions thrown
```shell
ERROR:root:StackdriverStatsExporter failed to emit data.Dropping 2 objects from queue.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/opencensus/common/transports/async.py", line 105, in _thread_main
    self.exporter.emit(data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 145, in emit
    self.handle_upload(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 157, in handle_upload
    self.upload_stats(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 166, in upload_stats
    request[CONS_TIME_SERIES])
  File "/usr/local/lib/python2.7/site-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 868, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
InvalidArgument: 400 One or more TimeSeries could not be written: Field timeSeries[0].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[0]; Field timeSeries[1].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[1]
ERROR:root:StackdriverStatsExporter failed to emit data.Dropping 10 objects from queue.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/opencensus/common/transports/async.py", line 105, in _thread_main
    self.exporter.emit(data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 145, in emit
    self.handle_upload(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 157, in handle_upload
    self.upload_stats(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 166, in upload_stats
    request[CONS_TIME_SERIES])
  File "/usr/local/lib/python2.7/site-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 868, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
InvalidArgument: 400 One or more TimeSeries could not be written: Field timeSeries[0].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[0]; Field timeSeries[1].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[1]; Field timeSeries[2].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[2]; Field timeSeries[3].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[3]; Field timeSeries[4].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[4]; Field timeSeries[5].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[5]; Field timeSeries[6].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[6]; Field timeSeries[7].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[7]; Field timeSeries[8].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[8]; Field timeSeries[9].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[9]
ERROR:root:StackdriverStatsExporter failed to emit data.Dropping 4 objects from queue.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/opencensus/common/transports/async.py", line 105, in _thread_main
    self.exporter.emit(data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 145, in emit
    self.handle_upload(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 157, in handle_upload
    self.upload_stats(view_data)
  File "/usr/local/lib/python2.7/site-packages/opencensus/stats/exporters/stackdriver_exporter.py", line 166, in upload_stats
    request[CONS_TIME_SERIES])
  File "/usr/local/lib/python2.7/site-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 868, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/gapic_v1/method.py", line 139, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/site-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/site-packages/google/api_core/timeout.py", line 206, in func_with_timeout
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/google/api_core/grpc_helpers.py", line 56, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "/usr/local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
InvalidArgument: 400 One or more TimeSeries could not be written: Field timeSeries[0].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[0]; Field timeSeries[1].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[1]; Field timeSeries[2].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[2]; Field timeSeries[3].points had an invalid value: Only one point can be written per TimeSeries per request.: timeSeries[3]
Background thread exited.
Sent all pending spans.
```

**Comment by mayurkale22** [comment]
@c24t 
I think current wait time for export interval is one second, Ideally this should be 60 secs. 

Default interval in Java : https://github.com/census-instrumentation/opencensus-java/blob/69360e984884902e60c0ffafe4c73a18702896ad/exporters/stats/stackdriver/src/main/java/io/opencensus/exporter/stats/stackdriver/StackdriverStatsExporter.java#L71

**Comment by c24t** [comment]
Dumping the `CreateTimeSeriesRequest`s that get created, it's clear we're trying to create a few `TimeSeries` with multiple points, which [`metrics.proto` says not to do](https://github.com/googleapis/googleapis/blob/master/google/monitoring/v3/metric.proto#L89-L93).

```
time_series {
  metric {
    type: "custom.googleapis.com/opencensus/pymemcache/calls"
  }
  resource {
    type: "global"
  }
  points {
    interval {
      start_time {
        seconds: 1539641779
        nanos: 354718923
      }
      end_time {
        seconds: 1539641780
        nanos: 354718923
      }
    }
    value {
      string_value: "pymemcache.client.base.Client.get"
    }
  }
  points {
    interval {
      start_time {
        seconds: 1539641779
        nanos: 354718923
      }
      end_time {
        seconds: 1539641780
        nanos: 354718923
      }
    }
    value {
      string_value: "pymemcache.client.base.Client.set"
    }
  }
  points {
    interval {
      start_time {
        seconds: 1539641779
        nanos: 354718923
      }
      end_time {
        seconds: 1539641780
        nanos: 354718923
      }
    }
    value {
      string_value: "pymemcache.client.base.Client.delete"
    }
  }
}
```
Still looking to see if this is the culprit, and when this behavior changed.
