### ISSUE TITLE
Kuberenetes stackdriver exporter problem

### ISSUE THREAD

**Issue by tuffk** [census-instrumentation/opencensus-python#381]
Hi I'm using trace for an app running in GCP kuberenetes clusters and I'm having some errors when sending the traces

here is the error form GCP:
```
TypeError: must be str, not bytes
 Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/transports/background_thread.py", line 106, in _thread_main
    self.exporter.emit(span_datas)
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 224, in emit
    stackdriver_spans = self.translate_to_stackdriver(trace)
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 248, in translate_to_stackdriver
    set_attributes(trace)
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 76, in set_attributes
    set_monitored_resource_attributes(span)
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 91, in set_monitored_resource_attributes
    'project_id')
  File "/usr/local/lib/python3.6/site-packages/opencensus/trace/exporters/stackdriver_exporter.py", line 136, in set_attribute_label
    label_value_prefix + resource_labels[attribute_key]
TypeError: must be str, not bytes
```
I have configured the env var `GOOGLE_APPLICATION_CREDENTIALS` to be the path to the json of the service account 

the container is based on `python:3.6.6-alpine` with `opencensus==0.1.8, google-cloud-trace==0.19.0, grpcio==1.16.0`

kubernetes version `1.9.7-gke.5`

I have tried creating a container in my localhost with the same settings and same service account and it sends the traces correctly to stackdriver

**Comment by liyanhui1228** [comment]
This is related to #367

**Comment by c24t** [comment]
@tuffk are you still seeing this error on master now that #365 is merged?

**Comment by tuffk** [comment]
@c24t  using master the problem is fixed, thank you

**Comment by c24t** [comment]
Glad to hear it!
