### ISSUE TITLE
exporter/stackdriver: reports zone as fully qualified resource

### ISSUE THREAD

**Issue by colincadams** [census-instrumentation/opencensus-python#533]
When running an app engine flex app, open census defaults reporting to the `gce_instance` monitored resource (seems fine) with `zone` set to the fully qualified zone returned from [the metadata api](https://cloud.google.com/compute/docs/storing-retrieving-metadata#default):

```
OpenCensus monitored resource: "{'type': 'gce_instance', 'labels': {'instance_id': '[instance-id]', 'project_id': '[project-id]', 'zone': 'projects/[numeric-project-id]/zones/us-east1-c'}}"
```

This causes all points to fail like this:

```
async_/_thread_main : StackdriverStatsExporter failed to emit data.Dropping 1 objects from queue.
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/grpc/_channel.py", line 550, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "One or more TimeSeries could not be written: Unrecognized region or location.: timeSeries[0]"
	debug_error_string = "{"created":"@1551716760.822772067","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1036,"grpc_message":"One or more TimeSeries could not be written: Unrecognized region or location.: timeSeries[0]","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/src/opencensus/opencensus/common/transports/async_.py", line 105, in _thread_main
    self.exporter.emit(data)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/src/opencensus/opencensus/stats/exporters/stackdriver_exporter.py", line 153, in emit
    self.handle_upload(view_data)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/src/opencensus/opencensus/stats/exporters/stackdriver_exporter.py", line 165, in handle_upload
    self.upload_stats(view_data)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/src/opencensus/opencensus/stats/exporters/stackdriver_exporter.py", line 177, in upload_stats
    time_series_batch)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/cloud/monitoring_v3/gapic/metric_service_client.py", line 897, in create_time_series
    request, retry=retry, timeout=timeout, metadata=metadata
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 143, in __call__
    return wrapped_func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/retry.py", line 270, in retry_wrapped_func
    on_error=on_error,
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/retry.py", line 179, in retry_target
    return target()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 One or more TimeSeries could not be written: Unrecognized region or location.: timeSeries[0]
```

I have a sample app that runs into this issue: https://github.com/colincadams/opencensus-example

**Comment by colincadams** [comment]
Note that this is at 85b4620
