### ISSUE TITLE
Suppress/clean up output during system tests

### ISSUE THREAD

**Issue by c24t** [census-instrumentation/opencensus-python#591]
Output to stdout from other threads doesn't get captured during tests. A few of our tests -- mostly integration tests -- write to stdout via unconfigured loggers.

I added a few tests that intentionally trigger errors on another thread in https://github.com/census-instrumentation/opencensus-python/pull/577, which cause this

```
ERROR:opencensus.metrics.transport:Error handling metric export
Traceback (most recent call last):
  File "/root/repo/opencensus/metrics/transport.py", line 52, in run
    while not self._stopped.wait(self.interval):
  File "/root/repo/opencensus/metrics/transport.py", line 93, in export_all
    export(get())
  File "/root/repo/.nox/unit-py-2-7/lib/python2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/root/repo/.nox/unit-py-2-7/lib/python2.7/site-packages/mock/mock.py", line 1118, in _mock_call
    raise effect
ValueError
```

to get written to stdout.

**Comment by reyang** [comment]
This seems to be addressed by #635. I'll keep this bug open since there are still some deprecation warnings (and some of them are tricky since we have to use the "deprecated version" in order to work with Python 2.x, unless we put conditional logic - which seems to be an overkill).
