### ISSUE TITLE
opencensus-context has no source distribution which causes pip `--no-binary` to fail

### ISSUE THREAD

**Issue by bshibs** [census-instrumentation/opencensus-python#849]
**Describe your environment.** OSX (though I believe this issue is OS-independent)

**Steps to reproduce.**

```
$ pipenv run pip --version
pip 19.3.1 from /.../virtualenvs/bsmining-_shFK90Q/lib/python3.7/site-packages/pip (python 3.7)

$ pip download --dest=/tmp --no-binary=:all: opencensus-context==0.1.1
ERROR: Could not find a version that satisfies the requirement opencensus-context==0.1.1 (from versions: none)
ERROR: No matching distribution found for opencensus-context==0.1.1
```

**What is the expected behavior?**
Successful download of the package.

**What is the actual behavior?**
See above

**Comment by bshibs** [comment]
Actually it looks like all setup.cfg files are only configured for wheel distribution.

**Comment by nareshv** [comment]
I am also stuck on this. Can your team release `sdist` packages ?

**Comment by glaubitz** [comment]
The missing source packages on PyPi also make packaging ```opencensus``` packages for Linux distributions much more difficult. I'm currently packaging it for openSUSE/SLE.

**Comment by f3flight** [comment]
Hi all! This is still an issue, because even though opencensus-context 0.1.2 source is available in pypi, it has been incorrectly packaged. The archive is missing "version.py" from the root dir, which makes the source unusable for installation purposes:
```
(venv) [user@venv]$ pip download --no-binary :all: opencensus-context==0.1.2
Collecting opencensus-context==0.1.2
  Downloading opencensus-context-0.1.2.tar.gz (3.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-download-sro3dga9/opencensus-context_176b691556044a638b14c037d5b7c4e9/setup.py", line 17, in <module>
          from version import __version__
      ModuleNotFoundError: No module named 'version'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
